name: Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  dev-deploy-preview:
    strategy:
      matrix:
        environment:
          [
            {
              name: development,
              bucket: "dev-design.va.gov/${{ github.event.number }}",
              config: dev.yml,
            },
          ]
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      github-sha: ${{ github.sha }}
      github-run-id: ${{ github.run_id }}
      github-event-number: ${{ github.event.number }}
      matrix-name: ${{ matrix.environment.name }}
      matrix-bucket: ${{ matrix.environment.bucket }}
      matrix-config: ${{ matrix.environment.config }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update PR Description
        uses: nefrob/pr-description@v1.2.0
        with:
          content: ${{ github.event.number }}
          regex: "PR_NUMBER.*"
          appendContentOnMatchOnly: true
          token: ${{ secrets.GITHUB_TOKEN }}
